Creating an apple website clone
alvinlouis29/Apple-websiteclone pull request #2
Opened 2020-02-28 15:04 UTC by alvinlouis29

the aim of this project is to create a clone of an apple old website of 2014 from http://archive.fo/UW4oR using CSS and Html

2020-02-28 17:46 UTC, kobiyoyo requested changes
## Hi @alvinlouis29       ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there are a few more things required. 
### General
- [ ] Check HTML markup with this validator https://validator.w3.org/#validate_by_upload. 
- [ ] The screenshot in the readme file is broken,lets fix that.
#### Navbar
* [ ] The Search field on the rightmost section should look similar to the original

#### Navigation background
* [ ] It uses CSS [`background -> gradient`](https://www.w3schools.com/cssref/css3_pr_background.asp) for background
### Original 
![1](https://user-images.githubusercontent.com/23278161/75571919-6ff36500-5a5a-11ea-980e-cdd4ffd5d9f1.png)

### Yours
![2](https://user-images.githubusercontent.com/23278161/75571924-741f8280-5a5a-11ea-8532-759fc12f88fd.png)

- [ ] This Four elements should look like the original
### Original 
![2](https://user-images.githubusercontent.com/23278161/75571075-c5c70d80-5a58-11ea-90d0-23a18804f058.png)
### Yours
![1](https://user-images.githubusercontent.com/23278161/75571086-cc558500-5a58-11ea-8c93-efacda9dd0ec.png)
#### Footer
- [ ] Kindly note the footer should look similar to the original
### Original 
![1](https://user-images.githubusercontent.com/23278161/75571634-ddeb5c80-5a59-11ea-8b3d-bdeb6dbab7bc.png)

### Yours
![2](https://user-images.githubusercontent.com/23278161/75571637-de83f300-5a59-11ea-9791-1a7bbbeefc8d.png)
- [ ] Elements should be aligned with [float](https://css-tricks.com/all-about-floats/) and [flex](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) or [grid](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout)

### Make changes and submit another code review request.
*Happy coding*

2020-02-29 02:44 UTC, majovanilla commented
### Code review under progress by Maria Reyes

2020-02-29 02:56 UTC, majovanilla commented
Hey @alvinlouis29 , 👋

## You did a *great* job implementing the required changes on this project! 💜 

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- Always remember to check your HTML using the [validator](https://validator.w3.org/). You have one error. Please fix it.
![Screenshot from 2020-02-28 20-48-36](https://user-images.githubusercontent.com/51926937/75599571-c026f300-5a6b-11ea-8173-419aefa3a383.png)

- Improve your Readme file. It should be descriptive of the project. You are using the right template! Just fill it up with the information about the great work you did here. And fix the screenshot as requested by @kobiyoyo , please!!

-Please write meaningful pull request messages. Check this [example](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)

- The search bar is not quite there yet. Please change the background so that it matches the original one. It should include the search icon, too. And it should have a rounded shape.

Your search bar:
![Screenshot from 2020-02-28 20-52-55](https://user-images.githubusercontent.com/51926937/75599627-62df7180-5a6c-11ea-9580-54154bec1b61.png)

Original search bar:
![Screenshot from 2020-02-28 20-53-25](https://user-images.githubusercontent.com/51926937/75599629-65da6200-5a6c-11ea-874b-08ab4aa8ab0b.png)

- You are using buttons on your navbar. That is not the right use of buttons (check [here](https://stackoverflow.com/questions/21715162/when-should-i-use-a-button-button-or-a-link-a-in-html) and [here](https://developer.mozilla.org/en/docs/Web/HTML/Element/button) for more on that. If you check the original page, the navbar has links `<a>` tags. Please change this.


### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  

These are completely [Optional]: 🦔

- You can add the hover effects to the text on the main image and the links on the footer.


## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes



You can find me on Social Media below 👇 . Remember to say hi!

[GitHub](https://github.com/majovanilla) [Twitter](https://twitter.com/MajoVanilla) [LinkedIn](https://www.linkedin.com/in/majoreyesparroquin/)

2020-07-14 05:13 UTC, elmejdki requested changes
# status: require changes :recycle: 
## Hi, @alvinlouis29 great job so far :clap: :+1: :100:, but :warning: I have seen that you skipped several requirements by the previous TSE :arrow_backward:, please return back and make them valid also align the apple logo inside the navbar it's not aligned correctly, and fix your stickler errors.

### Please make all the required changes before you request another code review.
## Happy Coding :tophat: 
_If you feel like stuck or need help don't hesitate to contact me on slack_

2020-07-14 20:18 UTC, tirthajyoti-ghosh requested changes
# Changes required 🛑 

## Impressive progress so far 💪! Thanks for making all the changes 👏.

### However, we need to work on some changes before we can merge.

- There is no live demo link in your project README. Please add that. Also, the screenshot is not displaying.
- The search icon in your navbar is not aligned properly. Please fix that to match the original.

   ![image](https://user-images.githubusercontent.com/57726348/87472183-27b99580-c63d-11ea-8221-3e42c864c4f8.png)

Your project looks absolutely fantastic. Just make these changes and apply for another code review.

Happy coding 👨‍💻 

-------------------------------------------------------------------------------------------------------------------

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

2020-07-15 03:23 UTC, voscarmv requested changes
# Impressive work! 🖥️ 👀 ✨ 
- Good job implementing the requested changes.
- Nice `README` file.

## However, some changes are still required... 🧰 🔨 🔧 

- Please fix the following HTML error found using the [Nu HTML validator](https://validator.w3.org/nu/#textarea)
![image](https://user-images.githubusercontent.com/2739245/87499555-35145700-c620-11ea-8f9f-c629726ca6a9.png)

- Please use a proper `<main>` semantic tag, as indicated on the code comments.

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2020-07-15 03:23 UTC, voscarmv commented on index.html
> +        <section class="main-content">
Please use a proper `<main>` semantic tag here, instead of just a `<section>` tag.

2020-07-15 14:51 UTC, bertil291utn commented
**Status:** Approved ✅
# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

 ## Ship it

<img src="https://i.cubeupload.com/4HbSFK.jpg" alt="image" width="100" />

Please merge to master branch and move on with the next assignment.

You're doing  a great job keep going 💻 🚀 🔥

**[TAKE IN MIND]**
Next projects:

- [ ] Be careful with README file, should be more professional
- [ ] Your commit messages are great, however your box message pull request should be like so: title follow by a description of what have you done.

Check again [this lesson](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) to improve these requirements



> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2020-07-15 15:02 UTC, merged